name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #macos-13] # macos-14, windows-latest, # mac arm needs MACOSX_DEPLOYMENT_TARGET 14 b/c of libs pulled via brew

    steps:
      - uses: actions/checkout@v4

    #   - name: Install SuiteSparse on MacOS
    #     if: runner.os == 'macOS'
    #     run: brew install suitesparse

      - name: Set up QEMU for aarch64 compilation on Linux
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Install conda on Windows
        if: runner.os == 'Windows'
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge, anaconda

      - name: Install SuiteSparse and Pkc-Config on Windows
        if: runner.os == 'Windows'
        run: conda install -y suitesparse pkgconfig

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl