name: test

on:
  - push
  - pull_request

jobs:

  maketest:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: clone SuiteSparse
        run: git clone -b stable --depth 1 https://github.com/DrTimothyAldenDavis/SuiteSparse.git

      # stuff to compile suitesparse; can also go with netlib BLAS/LAPACK, but
      # CHOLMOD uses LAPACK for supernodal ops, better to have a good one

      - name: install deps to compile SuiteSparse
        run: sudo apt install -y libmpfr-dev libopenblas-dev

      # - name: compile SuiteSparse
      #   run: |
      #        cd SuiteSparse #/SPQR
      #        make global

      # - name: install SuiteSparse
      #   run: |
      #        sudo make install
      #        cd ..
      - name: compile and install SuiteSparse
        run: |
             cd SuiteSparse/SuiteSparse_config
             make global
             sudo make install

             cd ../AMD
             make global
             sudo make install

             cd ../COLAMD
             make global
             sudo make install

             cd ../CAMD
             make global
             sudo make install

             cd ../CCOLAMD
             make global
             sudo make install

             cd ../CHOLMOD
             make global
             sudo make install

             cd ../SPQR
             make global
             sudo make install

             cd ../..

      - name: install Python deps and compile/test with Makefile
        run: |
             # sudo apt install -y libsuitesparse-dev
             pip install numpy
             make