name: test

on:
  - push
  - pull_request

jobs:

  maketest:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: test
        run: |
             git clone -b stable --depth 1 https://github.com/DrTimothyAldenDavis/SuiteSparse.git
             cd SuiteSparse #/SPQR
             # stuff to compile suitesparse
             sudo apt install -y libmpfr-dev
             make global
             sudo make install
             cd ..
             # sudo apt install -y libsuitesparse-dev
             pip install numpy
             make