name: test

on:
  - push
  - pull_request

jobs:

  maketest:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            check-latest: true 

      - name: test
        run: make